# Generated by Django 5.1.3 on 2024-11-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorprofile",
            name="registration_step",
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
