# Generated by Django 5.1.3 on 2024-11-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0002_remove_doctorprofile_registration_step_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="registration_step",
            field=models.IntegerField(default=1),
        ),
    ]
